### PR TITLE
Feature/kubernetes dev env

### PR DESCRIPTION
**Pull request by PabloPie**
Tests are welcome. Minikube and docker must be installed. Scripts have to be run as root. ~~Docker images have to be built beforehand with tag ":new" and with the config files in "configs/"~~. Images are now available at our registry.

### CODE REVIEW

**Comment by iamdey** [comment]
1/ it seems to be possible to not use sudo (or I don't understand well), I have this log:

```
Kubectl is now configured to use the cluster.
===================
WARNING: IT IS RECOMMENDED NOT TO RUN THE NONE DRIVER ON PERSONAL WORKSTATIONS
        The 'none' driver will run an insecure kubernetes apiserver as root that may leave the host vulnerable to CSRF attacks

When using the none driver, the kubectl config and credentials generated will be root owned and will appear in the root home directory.
You will need to move the files to the appropriate location and then set the correct permissions.  An example of this is below:

        sudo mv /root/.kube $HOME/.kube # this will write over any previous configuration
        sudo chown -R $USER $HOME/.kube
        sudo chgrp -R $USER $HOME/.kube

        sudo mv /root/.minikube $HOME/.minikube # this will write over any previous configuration
        sudo chown -R $USER $HOME/.minikube
        sudo chgrp -R $USER $HOME/.minikube

This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
```

2/ I got this error then:

```
Loading cached images from config file.

Configmap and secret creation
-----------------------------
error: error reading /home/dey/Workspace/src/backend/configs: no such file or directory
```

**Comment by PabloPie** [comment]
> 1/ it seems to be possible to not use sudo (or I don't understand well), I have this log:

That is just to be able to use kubectl without being root. Without a driver it is impossible to run without being root. [See this issue](https://github.com/kubernetes/kubeadm/issues/57).



> 2/ I got this error then:

Is your master branch up to date?

**Comment by iamdey** [comment]
new error:

```
cd devtools/kubernetes
➜  kubernetes git:(feature/kubernetes-dev-env) ✗ sudo ./deploy-minikube.sh                                                                                                        [4/184]
On Linux Minikube can be run on Virtualbox or locally with Docker, which one should be used? (v/d) d                                                                                     
Starting local Kubernetes v1.10.0 cluster...                                                                                                                                             
Starting VM...                                                                                                                                                                           
Getting VM IP address...                                                                                                                                                                 
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0515 15:44:49.386284   17096 start.go:276] Error starting cluster:  kubeadm init error sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable$
-etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=F$
leAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileA$
ailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  running command: : running command: sudo /usr/bin/kubeadm init --config /var/l$
b/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data --ignore-preflight-errors=FileAvailable--etc-kubernetes-man$
fests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-c$
ntroller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI
 output: [init] Using Kubernetes version: v1.10.0
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
        [WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 17.05.0-ce. Max validated version: 17.03
        [WARNING Hostname]: hostname "minikube" could not be reached
        [WARNING Hostname]: hostname "minikube" lookup minikube on 192.168.1.254:53: no such host
        [WARNING FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
        [WARNING FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
        [WARNING FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
        [WARNING FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
        [WARNING Swap]: running with swap on is not supported. Please disable swap
        [WARNING FileExisting-ebtables]: ebtables not found in system path
        [WARNING FileExisting-ethtool]: ethtool not found in system path
        [WARNING FileExisting-socat]: socat not found in system path
        [WARNING FileExisting-crictl]: crictl not found in system path
Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
Flag --admission-control has been deprecated, Use --enable-admission-plugins or --disable-admission-plugins instead. Will be removed in a future version.
        [WARNING DirAvailable--data]: /data is not empty
[preflight] Some fatal errors occurred:
        [ERROR Port-8443]: Port 8443 is in use
        [ERROR Port-10250]: Port 10250 is in use
        [ERROR Port-10251]: Port 10251 is in use
        [ERROR Port-10252]: Port 10252 is in use
        [ERROR Port-2379]: Port 2379 is in use
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
: running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--dat
a --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-pr
eflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors
=Swap --ignore-preflight-errors=CRI
.: exit status 2
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:
```

**Comment by iamdey** [comment]
previous error is ok after cleaning with `clean-minikube.sh`

new error then:

```
Configmap and secret creation
-----------------------------
configmap "caliopen-config" created
configmap "minio-config" created
configmap "kube-dns" created
error: error converting YAML to JSON: yaml: control characters are not allowed
```

**Comment by iamdey** [comment]
(may be the solution is to drop the support of docker if it requires too much effort to manage)

**Comment by PabloPie** [comment]
> after stopping or cleaning kube*, I'm not able to use docker-compose or whatever using a port used by k8s (e.g 31415 for the api) and get this kind of error:

That's weird, are you sure kubernetes was not running? Cleaning or even just stopping the cluster with ``` sudo minikube stop ``` frees the ports used by the cluster( ``` netstat -tulpn ``` doesn't show them as used ). Maybe it is related to your second problem?

> after rebooting the host (my machine) minikube is started (even if I've stoped minikube before). imo it should not happens on dev env.

You are right, it is an inconvenience having it start the cluster on boot. I don't really know what we can do in that matter. Cleaning is not an option because you may lose important data stored in your cluster.

> (may be the solution is to drop the support of docker if it requires too much effort to manage)

It is true that if run on a virtual machine you won't encounter many of this problems. Giving the option of running it locally doesn't take much on our side, but the developer has to be a little bit more careful as he may encounter some conflicts.

**Pull request merged**
