### PR TITLE
add the not found unicorn

### PR DESCRIPTION
**Pull request by iamdey**

### CODE REVIEW

**Comment by iamdey** [comment]
I can't reproduce your issue @myleneb. 
what's your browser ?

**Comment by myleneb** [comment]
Chromium Version 64.0.3282.186 and it also bugs with epiphany ( = WebKit)

**Comment by iamdey** [comment]
I've checked those browsers. Is it still the case ?

**Comment by iamdey** [comment]
I was able to see it on saucelabs

0021screenshot

**Comment by myleneb** [comment]
There are browsers' related issues due to monospace font:

> Major web browsers automatically reduce the size of monospace text in a range of situations. They do this due to the greater width of many monospace typefaces in comparison to other fonts at the same text height. While well-intentioned, their handling of monospace fonts is fundamentally broken, and an unusual CSS rule is required to fix the problem.

http://code.iamkate.com/html-and-css/fixing-browsers-broken-monospace-font-handling/

the hack `font-family:monospace,monospace;` seems to work for my chromium issue but not for epiphany.

**Comment by iamdey** [comment]
if we reduce the size of the font of this element, does it work fine ?

**Comment by myleneb** [comment]
see https://github.com/CaliOpen/Caliopen/pull/876

**Pull request merged**
