### PR TITLE
Features/dockerize api

### PR DESCRIPTION
**Pull request by gdchamal**
The return of API and CLI in docker containers

### CODE REVIEW

**Comment by gdchamal** [comment]
I don't understand the point with empty line at end of file

For the compose version it should be fixed, also the docker compose stack scenario is a bit described in the README.

**Comment by iamdey** [comment]
I don't knew why for the empty line, but it sounds a pretty good convention: http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline#729795

**Comment by gdchamal** [comment]
Files (most of) have an empty line, but it does not appear in github when displaying one of them (caliopen-docker.yaml for example)

**Comment by iamdey** [comment]
Oh, you were right about empty line. Github put a red new line icon when it is missing. I saw some before. well not big deal.

**Pull request merged**
