### PR TITLE
Feature/backend/unfiltered messages list

### PR DESCRIPTION
**Pull request by sapiens-sapide**
To allow frontend to render the 'hammer' timeline, ie. unfiltered messages list.

### CODE REVIEW

**Comment by iamdey** [comment]
can you add `excerpt` prop (like in discussion) ?

**Comment by sapiens-sapide** [comment]
excerpt is a discussion property. We do not have discussions object on this route.

**Comment by iamdey** [comment]
excerpt is able to extract raw text from a mail to display it on the timeline. We still need it for the hammer.

If you can't extract it, it will be done client side (no idea how).

**Comment by sapiens-sapide** [comment]
Following today's morning meeting, we'll modify API to return Message object with a new property : `excerpt`.

**Pull request merged**
