### PR TITLE
We can define a configuration file to whitelist allowed user recovery…

### PR DESCRIPTION
**Pull request by gdchamal**
… email for registration

### CODE REVIEW

**Comment by gdchamal** [comment]
That a first whitelist strategy a minima.
If we need to add random it will be easy

For user feedback when it fail, the API raise a 401 with an error message that email is not in whitelist. You want another HTTP code ?

**Comment by iamdey** [comment]
we need some frontend adjustments, the feedback from api is not displayed as is in the frontend.

**Comment by sapiens-sapide** [comment]
This code allows an user to create more than one account with the same `recovery_email`. Is it ok ?

**Comment by gdchamal** [comment]
For frontend impact, I think we can only display a disclosure message that you must have a registered email (display a link to alpha subscribe form)

About multiple account with the same recovery email, I think it's not a problem

**Pull request merged**
