### PR TITLE
Fix/frontend/attachements visibility

### PR DESCRIPTION
**Pull request by iamdey**

### CODE REVIEW

**Comment by MonsieurLanza** [comment]
Yes, but : encrypted message always have 2 empty attachments (encrypted.asc & "unknown"), due to the way the backend treats MIME envelope, which are not real attachments. So we should provide a way to not display those, or to fix backend.

**Comment by iamdey** [comment]
I prefer the 2nd solution, fix the backend :D 
@sapiens-sapide

**Comment by sapiens-sapide** [comment]
are these attachments « inline » ? If yes, is it the same issue that @iamdey encounter when testing inline images ?

**Comment by MonsieurLanza** [comment]
encrypted.asc has `Content-Disposition: inline`. I am not sure about the other one.

**Pull request merged**
