### PR TITLE
Upgrade/backend/elasticsearch

### PR DESCRIPTION
**Pull request by gdchamal**
Using official elasticsearch v5.x image need usage of docker volumes (https://docs.docker.com/engine/reference/commandline/volume_create/#parent-command)

A previous merge to upgrade to es 5.4.1 forgot that needed update and make es container does not work anymore on linux platform with our volume usage in docker compose.

### CODE REVIEW

**Comment by gdchamal** [comment]
Need to tune a bit linux host kernel issuing this command:

```
sudo sysctl -w vm.max_map_count=262144
```

in case elasticsearch container does not start with this type of error:
https://github.com/docker-library/elasticsearch/issues/111

**Comment by sapiens-sapide** [comment]
LGTM. (re)-tested on OSX.

**Comment by iamdey** [comment]
how do we reset datas with this config ?

**Comment by sapiens-sapide** [comment]
resetting data is documented in another branch : `doc/backend/docker-stack`

**Pull request merged**
